// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

/**
 * @title IOrganizationRegistry
 * @dev Interface for OrganizationRegistry contract to enable clean integration with other contracts
 * @notice This interface will be used by CarbonCreditNFT, verifier contracts, and other integrations
 * @author VeChain Builders Hackathon Team
 */
interface IOrganizationRegistry {
    // Enums (must be redeclared in interface)
    enum VerificationStatus {
        Pending,
        Verified,
        Rejected,
        Suspended
    }

    // Struct for return types
    struct OrganizationProfile {
        uint256 orgId;                    // Unique organization identifier
        string name;                      // Organization name
        address walletAddress;            // Primary wallet address
        VerificationStatus verificationStatus; // Current verification status
        uint256 totalCreditsGenerated;    // Total carbon credits generated by this org
        string kycDocumentsHash;          // IPFS hash of KYC documents
        uint256 registrationDate;         // Unix timestamp of registration
        uint256 lastUpdated;              // Unix timestamp of last update
        bool isActive;                    // Whether the organization is active
    }

    // Function signatures (external functions only)
    function registerOrganization(
        string memory name,
        address walletAddress,
        string memory kycDocumentsHash
    ) external returns (uint256);

    function updateOrganization(
        uint256 orgId,
        string memory name,
        string memory kycDocumentsHash
    ) external;

    function verifyOrganization(
        uint256 orgId,
        VerificationStatus newStatus
    ) external;

    function setOrganizationStatus(
        uint256 orgId,
        bool isActive
    ) external;

    function updateCreditsGenerated(
        uint256 orgId,
        uint256 additionalCredits
    ) external;

    function getOrganization(uint256 orgId) external view returns (OrganizationProfile memory);

    function getOrgIdByAddress(address walletAddress) external view returns (uint256);

    function getOrgIdByName(string memory name) external view returns (uint256);

    function isOrganizationVerified(uint256 orgId) external view returns (bool);

    function isOrganizationActive(uint256 orgId) external view returns (bool);

    function getTotalOrganizations() external view returns (uint256);

    function getActiveOrganizationIds() external view returns (uint256[] memory);

    function getVerificationStatus(uint256 orgId) external view returns (VerificationStatus);

    function getTotalCreditsGenerated(uint256 orgId) external view returns (uint256);

    function isAddressRegistered(address walletAddress) external view returns (bool);

    function isNameTaken(string memory name) external view returns (bool);

    // Events (must be declared in interface for external contracts to reference)
    event OrganizationRegistered(
        uint256 indexed orgId,
        address indexed walletAddress,
        string name,
        string kycDocumentsHash
    );

    event OrganizationUpdated(
        uint256 indexed orgId,
        address indexed walletAddress,
        string name
    );

    event OrganizationVerified(
        uint256 indexed orgId,
        VerificationStatus oldStatus,
        VerificationStatus newStatus
    );

    event OrganizationSuspended(
        uint256 indexed orgId,
        bool isActive
    );

    event CreditsGeneratedUpdated(
        uint256 indexed orgId,
        uint256 oldAmount,
        uint256 newAmount
    );
}
