import { Connex } from '@vechain/connex';
import { ethers } from 'ethers';
import { VeChainCarbonCreditSDK } from '../VeChainSDK';

/**
 * Organization Registry Module
 * Handles all interactions with the OrganizationRegistry contract
 */

export interface RegisterOrganizationParams {
  name: string;
  walletAddress: string;
  kycDocumentsHash: string;
}

export interface UpdateOrganizationParams {
  orgId: number;
  name: string;
  walletAddress: string;
  kycDocumentsHash: string;
}

export interface VerifyOrganizationParams {
  orgId: number;
  verificationStatus: number;
}

export interface SetOrganizationStatusParams {
  orgId: number;
  status: number;
}

export class OrganizationRegistryModule {
  private sdk: VeChainCarbonCreditSDK;
  private contractAddress: string;

  constructor(sdk: VeChainCarbonCreditSDK) {
    this.sdk = sdk;
    this.contractAddress = sdk.getContractAddresses().organizationRegistry;
  }

  /**
   * Register a new organization
   */
  async registerOrganization(params: RegisterOrganizationParams): Promise<string> {
    const method = this.sdk['config'].connex.thor.account(this.contractAddress).method({
      constant: false,
      inputs: [
        { name: 'name', type: 'string' },
        { name: 'walletAddress', type: 'address' },
        { name: 'kycDocumentsHash', type: 'string' }
      ],
      name: 'registerOrganization',
      outputs: [{ name: '', type: 'uint256' }],
      payable: false,
      stateMutability: 'nonpayable',
      type: 'function'
    });

    const clause = method.asClause(
      params.name,
      params.walletAddress,
      params.kycDocumentsHash
    );

    return await this.executeTransaction([clause]);
  }

  /**
   * Update organization information
   */
  async updateOrganization(params: UpdateOrganizationParams): Promise<string> {
    const method = this.sdk['config'].connex.thor.account(this.contractAddress).method({
      constant: false,
      inputs: [
        { name: 'orgId', type: 'uint256' },
        { name: 'name', type: 'string' },
        { name: 'walletAddress', type: 'address' },
        { name: 'kycDocumentsHash', type: 'string' }
      ],
      name: 'updateOrganization',
      outputs: [],
      payable: false,
      stateMutability: 'nonpayable',
      type: 'function'
    });

    const clause = method.asClause(
      params.orgId,
      params.name,
      params.walletAddress,
      params.kycDocumentsHash
    );

    return await this.executeTransaction([clause]);
  }

  /**
   * Verify organization
   */
  async verifyOrganization(params: VerifyOrganizationParams): Promise<string> {
    const method = this.sdk['config'].connex.thor.account(this.contractAddress).method({
      constant: false,
      inputs: [
        { name: 'orgId', type: 'uint256' },
        { name: 'verificationStatus', type: 'uint8' }
      ],
      name: 'verifyOrganization',
      outputs: [],
      payable: false,
      stateMutability: 'nonpayable',
      type: 'function'
    });

    const clause = method.asClause(params.orgId, params.verificationStatus);
    return await this.executeTransaction([clause]);
  }

  /**
   * Set organization status
   */
  async setOrganizationStatus(params: SetOrganizationStatusParams): Promise<string> {
    const method = this.sdk['config'].connex.thor.account(this.contractAddress).method({
      constant: false,
      inputs: [
        { name: 'orgId', type: 'uint256' },
        { name: 'status', type: 'uint8' }
      ],
      name: 'setOrganizationStatus',
      outputs: [],
      payable: false,
      stateMutability: 'nonpayable',
      type: 'function'
    });

    const clause = method.asClause(params.orgId, params.status);
    return await this.executeTransaction([clause]);
  }

  /**
   * Update credits generated by organization
   */
  async updateCreditsGenerated(orgId: number, additionalCredits: string): Promise<string> {
    const method = this.sdk['config'].connex.thor.account(this.contractAddress).method({
      constant: false,
      inputs: [
        { name: 'orgId', type: 'uint256' },
        { name: 'additionalCredits', type: 'uint256' }
      ],
      name: 'updateCreditsGenerated',
      outputs: [],
      payable: false,
      stateMutability: 'nonpayable',
      type: 'function'
    });

    const clause = method.asClause(orgId, additionalCredits);
    return await this.executeTransaction([clause]);
  }

  /**
   * Get organization profile
   */
  async getOrganizationProfile(orgId: number) {
    return await this.sdk.getOrganizationProfile(orgId);
  }

  /**
   * Get organization by wallet address
   */
  async getOrganizationByWallet(walletAddress: string): Promise<number> {
    const method = this.sdk['config'].connex.thor.account(this.contractAddress).method({
      constant: true,
      inputs: [{ name: 'walletAddress', type: 'address' }],
      name: 'getOrganizationByWallet',
      outputs: [{ name: '', type: 'uint256' }],
      payable: false,
      stateMutability: 'view',
      type: 'function'
    });

    const result = await method.call(walletAddress);
    return parseInt(result[0].toString());
  }

  /**
   * Check if organization exists
   */
  async organizationExists(orgId: number): Promise<boolean> {
    const method = this.sdk['config'].connex.thor.account(this.contractAddress).method({
      constant: true,
      inputs: [{ name: 'orgId', type: 'uint256' }],
      name: 'organizationExists',
      outputs: [{ name: '', type: 'bool' }],
      payable: false,
      stateMutability: 'view',
      type: 'function'
    });

    const result = await method.call(orgId);
    return result[0];
  }

  /**
   * Get total number of organizations
   */
  async getTotalOrganizations(): Promise<number> {
    const method = this.sdk['config'].connex.thor.account(this.contractAddress).method({
      constant: true,
      inputs: [],
      name: 'getTotalOrganizations',
      outputs: [{ name: '', type: 'uint256' }],
      payable: false,
      stateMutability: 'view',
      type: 'function'
    });

    const result = await method.call();
    return parseInt(result[0].toString());
  }

  /**
   * Get all organization IDs
   */
  async getAllOrganizationIds(): Promise<number[]> {
    const total = await this.getTotalOrganizations();
    const orgIds: number[] = [];
    
    for (let i = 1; i <= total; i++) {
      try {
        const exists = await this.organizationExists(i);
        if (exists) {
          orgIds.push(i);
        }
      } catch (error) {
        // Organization doesn't exist
        continue;
      }
    }
    
    return orgIds;
  }

  /**
   * Get organizations by verification status
   */
  async getOrganizationsByStatus(verificationStatus: number): Promise<number[]> {
    const allOrgIds = await this.getAllOrganizationIds();
    const filteredOrgIds: number[] = [];
    
    for (const orgId of allOrgIds) {
      try {
        const profile = await this.getOrganizationProfile(orgId);
        if (profile.verificationStatus === verificationStatus) {
          filteredOrgIds.push(orgId);
        }
      } catch (error) {
        // Organization doesn't exist or error occurred
        continue;
      }
    }
    
    return filteredOrgIds;
  }

  /**
   * Get verified organizations
   */
  async getVerifiedOrganizations(): Promise<number[]> {
    return await this.getOrganizationsByStatus(1); // 1 = Verified
  }

  /**
   * Get pending organizations
   */
  async getPendingOrganizations(): Promise<number[]> {
    return await this.getOrganizationsByStatus(0); // 0 = Pending
  }

  /**
   * Get rejected organizations
   */
  async getRejectedOrganizations(): Promise<number[]> {
    return await this.getOrganizationsByStatus(2); // 2 = Rejected
  }

  /**
   * Search organizations by name
   */
  async searchOrganizationsByName(searchTerm: string): Promise<number[]> {
    const allOrgIds = await this.getAllOrganizationIds();
    const matchingOrgIds: number[] = [];
    
    for (const orgId of allOrgIds) {
      try {
        const profile = await this.getOrganizationProfile(orgId);
        if (profile.name.toLowerCase().includes(searchTerm.toLowerCase())) {
          matchingOrgIds.push(orgId);
        }
      } catch (error) {
        // Organization doesn't exist or error occurred
        continue;
      }
    }
    
    return matchingOrgIds;
  }

  /**
   * Get organization statistics
   */
  async getOrganizationStatistics(): Promise<{
    totalOrganizations: number;
    verifiedOrganizations: number;
    pendingOrganizations: number;
    rejectedOrganizations: number;
    totalCreditsGenerated: string;
  }> {
    const total = await this.getTotalOrganizations();
    const verified = await this.getVerifiedOrganizations();
    const pending = await this.getPendingOrganizations();
    const rejected = await this.getRejectedOrganizations();
    
    // Calculate total credits generated
    let totalCredits = '0';
    const allOrgIds = await this.getAllOrganizationIds();
    
    for (const orgId of allOrgIds) {
      try {
        const profile = await this.getOrganizationProfile(orgId);
        totalCredits = (BigInt(totalCredits) + BigInt(profile.totalCreditsGenerated)).toString();
      } catch (error) {
        // Organization doesn't exist or error occurred
        continue;
      }
    }
    
    return {
      totalOrganizations: total,
      verifiedOrganizations: verified.length,
      pendingOrganizations: pending.length,
      rejectedOrganizations: rejected.length,
      totalCreditsGenerated: totalCredits
    };
  }

  /**
   * Execute transaction with fee delegation if enabled
   */
  private async executeTransaction(clauses: any[]): Promise<string> {
    if (!this.sdk['config'].wallet) {
      throw new Error('Wallet not configured');
    }

    const wallet = this.sdk['config'].wallet;
    
    // Use fee delegation if enabled
    if (this.sdk.isFeeDelegationEnabled() && this.sdk.getFeeDelegationManager()) {
      const feeDelegation = this.sdk.getFeeDelegationManager()!;
      const gasLimit = 300000; // Default gas limit for registry operations
      
      return await feeDelegation.signAndSendWithDelegation(
        { clauses },
        wallet,
        gasLimit
      );
    } else {
      // Regular transaction
      const tx = {
        clauses,
        gas: 300000,
        gasPrice: '0x0'
      };

      const signedTx = await wallet.signTransaction(tx);
      const result = await this.sdk['config'].connex.thor.transaction(signedTx).send();
      return result.txid;
    }
  }
}

export default OrganizationRegistryModule;
