// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/AccessControl.sol";

/**
 * @title OrganizationRegistry
 * @dev Registry contract for managing organization profiles in the carbon credit system
 * @notice Organizations can register, update their profiles, and track their carbon credit generation
 * @author VeChain Builders Hackathon Team
 */
contract OrganizationRegistry is AccessControl {

    // Role definitions
    bytes32 public constant VERIFIER_ROLE = keccak256("VERIFIER_ROLE");

    // Enums
    enum VerificationStatus {
        Pending,
        Verified,
        Rejected,
        Suspended
    }

    // Organization profile structure
    struct OrganizationProfile {
        uint256 orgId;                    // Unique organization identifier
        string name;                      // Organization name
        address walletAddress;            // Primary wallet address
        VerificationStatus verificationStatus; // Current verification status
        uint256 totalCreditsGenerated;    // Total carbon credits generated by this org
        string kycDocumentsHash;          // IPFS hash of KYC documents
        uint256 registrationDate;         // Unix timestamp of registration
        uint256 lastUpdated;              // Unix timestamp of last update
        bool isActive;                    // Whether the organization is active
    }

    // State variables
    uint256 private _orgIdCounter;
    mapping(uint256 => OrganizationProfile) private _organizations;
    mapping(address => uint256) private _addressToOrgId;
    mapping(string => uint256) private _nameToOrgId;
    uint256[] private _activeOrgIds;

    // Events
    event OrganizationRegistered(
        uint256 indexed orgId,
        address indexed walletAddress,
        string name,
        string kycDocumentsHash
    );

    event OrganizationUpdated(
        uint256 indexed orgId,
        address indexed walletAddress,
        string name
    );

    event OrganizationVerified(
        uint256 indexed orgId,
        VerificationStatus oldStatus,
        VerificationStatus newStatus
    );

    event OrganizationSuspended(
        uint256 indexed orgId,
        bool isActive
    );

    event CreditsGeneratedUpdated(
        uint256 indexed orgId,
        uint256 oldAmount,
        uint256 newAmount
    );

    // Modifiers
    modifier onlyExistingOrg(uint256 orgId) {
        require(_organizations[orgId].orgId != 0, "OrganizationRegistry: organization does not exist");
        _;
    }

    modifier onlyActiveOrg(uint256 orgId) {
        require(_organizations[orgId].isActive, "OrganizationRegistry: organization is not active");
        _;
    }

    /**
     * @dev Constructor
     */
    constructor() {
        _grantRole(DEFAULT_ADMIN_ROLE, msg.sender);
        _grantRole(VERIFIER_ROLE, msg.sender);
    }

    /**
     * @dev Register a new organization
     * @param name The organization name
     * @param walletAddress The primary wallet address
     * @param kycDocumentsHash IPFS hash of KYC documents
     * @return The assigned organization ID
     */
    function registerOrganization(
        string memory name,
        address walletAddress,
        string memory kycDocumentsHash
    ) external returns (uint256) {
        require(walletAddress != address(0), "OrganizationRegistry: wallet address cannot be zero");
        require(bytes(name).length > 0, "OrganizationRegistry: name cannot be empty");
        require(bytes(kycDocumentsHash).length > 0, "OrganizationRegistry: KYC documents hash cannot be empty");
        require(_addressToOrgId[walletAddress] == 0, "OrganizationRegistry: wallet address already registered");
        require(_nameToOrgId[name] == 0, "OrganizationRegistry: organization name already exists");

        _orgIdCounter++;
        uint256 orgId = _orgIdCounter;

        OrganizationProfile memory newOrg = OrganizationProfile({
            orgId: orgId,
            name: name,
            walletAddress: walletAddress,
            verificationStatus: VerificationStatus.Pending,
            totalCreditsGenerated: 0,
            kycDocumentsHash: kycDocumentsHash,
            registrationDate: block.timestamp,
            lastUpdated: block.timestamp,
            isActive: true
        });

        _organizations[orgId] = newOrg;
        _addressToOrgId[walletAddress] = orgId;
        _nameToOrgId[name] = orgId;
        _activeOrgIds.push(orgId);

        emit OrganizationRegistered(orgId, walletAddress, name, kycDocumentsHash);
        return orgId;
    }

    /**
     * @dev Update organization profile (only by organization wallet or admin)
     * @param orgId The organization ID
     * @param name The new organization name
     * @param kycDocumentsHash The new KYC documents hash
     */
    function updateOrganization(
        uint256 orgId,
        string memory name,
        string memory kycDocumentsHash
    ) external onlyExistingOrg(orgId) onlyActiveOrg(orgId) {
        OrganizationProfile storage org = _organizations[orgId];
        
        require(
            org.walletAddress == msg.sender || hasRole(DEFAULT_ADMIN_ROLE, msg.sender),
            "OrganizationRegistry: caller is not authorized to update this organization"
        );
        require(bytes(name).length > 0, "OrganizationRegistry: name cannot be empty");
        require(bytes(kycDocumentsHash).length > 0, "OrganizationRegistry: KYC documents hash cannot be empty");

        // If name is changing, check for duplicates
        if (keccak256(bytes(org.name)) != keccak256(bytes(name))) {
            require(_nameToOrgId[name] == 0, "OrganizationRegistry: organization name already exists");
            delete _nameToOrgId[org.name];
            _nameToOrgId[name] = orgId;
        }

        org.name = name;
        org.kycDocumentsHash = kycDocumentsHash;
        org.lastUpdated = block.timestamp;

        emit OrganizationUpdated(orgId, org.walletAddress, name);
    }

    /**
     * @dev Verify organization (only by verifiers)
     * @param orgId The organization ID
     * @param newStatus The new verification status
     */
    function verifyOrganization(
        uint256 orgId,
        VerificationStatus newStatus
    ) external onlyRole(VERIFIER_ROLE) onlyExistingOrg(orgId) {
        OrganizationProfile storage org = _organizations[orgId];
        VerificationStatus oldStatus = org.verificationStatus;
        
        org.verificationStatus = newStatus;
        org.lastUpdated = block.timestamp;

        emit OrganizationVerified(orgId, oldStatus, newStatus);
    }

    /**
     * @dev Suspend or reactivate organization (only by admins)
     * @param orgId The organization ID
     * @param isActive The new active status
     */
    function setOrganizationStatus(
        uint256 orgId,
        bool isActive
    ) external onlyRole(DEFAULT_ADMIN_ROLE) onlyExistingOrg(orgId) {
        OrganizationProfile storage org = _organizations[orgId];
        org.isActive = isActive;
        org.lastUpdated = block.timestamp;

        emit OrganizationSuspended(orgId, isActive);
    }

    /**
     * @dev Update total credits generated (only by authorized contracts)
     * @param orgId The organization ID
     * @param additionalCredits The additional credits to add
     */
    function updateCreditsGenerated(
        uint256 orgId,
        uint256 additionalCredits
    ) external onlyExistingOrg(orgId) onlyActiveOrg(orgId) {
        // This function will be called by the CarbonCreditNFT contract
        // In Phase 3, we'll add proper access control for the NFT contract
        OrganizationProfile storage org = _organizations[orgId];
        uint256 oldAmount = org.totalCreditsGenerated;
        org.totalCreditsGenerated += additionalCredits;
        org.lastUpdated = block.timestamp;

        emit CreditsGeneratedUpdated(orgId, oldAmount, org.totalCreditsGenerated);
    }

    /**
     * @dev Get organization profile by ID
     * @param orgId The organization ID
     * @return The organization profile
     */
    function getOrganization(uint256 orgId) external view onlyExistingOrg(orgId) returns (OrganizationProfile memory) {
        return _organizations[orgId];
    }

    /**
     * @dev Get organization ID by wallet address
     * @param walletAddress The wallet address
     * @return The organization ID (0 if not found)
     */
    function getOrgIdByAddress(address walletAddress) external view returns (uint256) {
        return _addressToOrgId[walletAddress];
    }

    /**
     * @dev Get organization ID by name
     * @param name The organization name
     * @return The organization ID (0 if not found)
     */
    function getOrgIdByName(string memory name) external view returns (uint256) {
        return _nameToOrgId[name];
    }

    /**
     * @dev Check if organization is verified
     * @param orgId The organization ID
     * @return Whether the organization is verified
     */
    function isOrganizationVerified(uint256 orgId) external view onlyExistingOrg(orgId) returns (bool) {
        return _organizations[orgId].verificationStatus == VerificationStatus.Verified;
    }

    /**
     * @dev Check if organization is active
     * @param orgId The organization ID
     * @return Whether the organization is active
     */
    function isOrganizationActive(uint256 orgId) external view onlyExistingOrg(orgId) returns (bool) {
        return _organizations[orgId].isActive;
    }

    /**
     * @dev Get total number of registered organizations
     * @return The total count
     */
    function getTotalOrganizations() external view returns (uint256) {
        return _orgIdCounter;
    }

    /**
     * @dev Get all active organization IDs
     * @return Array of active organization IDs
     */
    function getActiveOrganizationIds() external view returns (uint256[] memory) {
        return _activeOrgIds;
    }

    /**
     * @dev Get organization verification status
     * @param orgId The organization ID
     * @return The verification status
     */
    function getVerificationStatus(uint256 orgId) external view onlyExistingOrg(orgId) returns (VerificationStatus) {
        return _organizations[orgId].verificationStatus;
    }

    /**
     * @dev Get organization total credits generated
     * @param orgId The organization ID
     * @return The total credits generated
     */
    function getTotalCreditsGenerated(uint256 orgId) external view onlyExistingOrg(orgId) returns (uint256) {
        return _organizations[orgId].totalCreditsGenerated;
    }

    /**
     * @dev Check if wallet address is registered
     * @param walletAddress The wallet address to check
     * @return Whether the address is registered
     */
    function isAddressRegistered(address walletAddress) external view returns (bool) {
        return _addressToOrgId[walletAddress] != 0;
    }

    /**
     * @dev Check if organization name is taken
     * @param name The organization name to check
     * @return Whether the name is taken
     */
    function isNameTaken(string memory name) external view returns (bool) {
        return _nameToOrgId[name] != 0;
    }
}
