// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "@openzeppelin/contracts/access/AccessControl.sol";
import "@openzeppelin/contracts/token/ERC20/IERC20.sol";
import "@openzeppelin/contracts/token/ERC20/utils/SafeERC20.sol";
import "@openzeppelin/contracts/utils/ReentrancyGuard.sol";
import "./CarbonCreditNFT.sol";

/**
 * @title VeBetterIntegration
 * @dev Integrates with VeBetter DAO to distribute B3TR token rewards for carbon credit generation
 * @notice Rewards users with B3TR tokens based on their carbon credit contributions
 * @author VeChain Builders Hackathon Team
 */
contract VeBetterIntegration is AccessControl, ReentrancyGuard {
    using SafeERC20 for IERC20;

    // Role definitions
    bytes32 public constant REWARD_MANAGER_ROLE = keccak256("REWARD_MANAGER_ROLE");
    bytes32 public constant CLAIM_MANAGER_ROLE = keccak256("CLAIM_MANAGER_ROLE");

    // B3TR Token contract address (VeChain mainnet)
    address public constant B3TR_TOKEN = 0x5ef79995FE8a89e0812330E4378eB2660ceDe699;
    
    // External contract references
    CarbonCreditNFT public carbonCreditNFT;

    // Reward configuration
    struct RewardConfig {
        uint256 baseRewardPerTonne;      // Base B3TR reward per tonne of carbon (wei precision)
        uint256 bonusMultiplier;         // Bonus multiplier for verified credits (in basis points, 10000 = 100%)
        uint256 maxRewardPerTonne;       // Maximum reward per tonne (cap)
        uint256 minCarbonAmount;         // Minimum carbon amount to earn rewards
        bool isActive;                   // Whether rewards are currently active
        uint256 totalRewardsDistributed; // Total B3TR rewards distributed
        uint256 totalCarbonRewarded;     // Total carbon amount that earned rewards
    }

    // User reward tracking
    struct UserRewardInfo {
        uint256 totalEarned;             // Total B3TR earned by user
        uint256 totalClaimed;            // Total B3TR claimed by user
        uint256 pendingRewards;          // Pending B3TR to claim
        uint256 lastClaimTime;           // Last time user claimed rewards
        uint256 totalCarbonCredits;      // Total carbon credits generated by user
        uint256 rewardEligibleCredits;   // Carbon credits eligible for rewards
        bool isActive;                   // Whether user is eligible for rewards
    }

    // Credit reward tracking
    struct CreditRewardInfo {
        uint256 tokenId;                 // Carbon credit NFT token ID
        address user;                    // User who generated the credit
        uint256 carbonAmount;            // Carbon amount in tonnes
        uint256 b3trReward;              // B3TR reward amount
        uint256 timestamp;               // When reward was calculated
        bool isClaimed;                  // Whether reward has been claimed
        bool isVerified;                 // Whether credit is verified
    }

    // State variables
    RewardConfig public rewardConfig;
    mapping(address => UserRewardInfo) private _userRewards;
    mapping(uint256 => CreditRewardInfo) private _creditRewards;
    mapping(address => uint256[]) private _userCredits; // user => array of token IDs
    
    uint256[] private _allRewardedCredits;
    uint256 private _totalUsers;
    address[] private _activeUsers;

    // Events
    event RewardConfigUpdated(
        uint256 baseRewardPerTonne,
        uint256 bonusMultiplier,
        uint256 maxRewardPerTonne,
        bool isActive
    );

    event CarbonCreditRewarded(
        uint256 indexed tokenId,
        address indexed user,
        uint256 carbonAmount,
        uint256 b3trReward,
        bool isVerified
    );

    event RewardsClaimed(
        address indexed user,
        uint256 amount,
        uint256 timestamp
    );

    event UserActivated(
        address indexed user,
        bool isActive
    );

    event B3TRDeposited(
        address indexed depositor,
        uint256 amount
    );

    event EmergencyWithdraw(
        address indexed to,
        uint256 amount
    );

    // Modifiers
    modifier onlyActiveRewards() {
        require(rewardConfig.isActive, "VeBetterIntegration: rewards are not active");
        _;
    }

    modifier onlyValidTokenId(uint256 tokenId) {
        require(carbonCreditNFT.ownerOf(tokenId) != address(0), "VeBetterIntegration: invalid token ID");
        _;
    }

    modifier onlyRewardEligible(address user) {
        require(_userRewards[user].isActive, "VeBetterIntegration: user not eligible for rewards");
        _;
    }

    /**
     * @dev Constructor
     * @param _carbonCreditNFT Address of the CarbonCreditNFT contract
     */
    constructor(
        address _carbonCreditNFT
    ) {
        require(_carbonCreditNFT != address(0), "VeBetterIntegration: invalid NFT contract address");

        carbonCreditNFT = CarbonCreditNFT(_carbonCreditNFT);

        _grantRole(DEFAULT_ADMIN_ROLE, msg.sender);
        _grantRole(REWARD_MANAGER_ROLE, msg.sender);
        _grantRole(CLAIM_MANAGER_ROLE, msg.sender);

        // Initialize reward configuration
        rewardConfig = RewardConfig({
            baseRewardPerTonne: 100e18,      // 100 B3TR per tonne
            bonusMultiplier: 15000,          // 150% bonus for verified credits (15000 basis points)
            maxRewardPerTonne: 500e18,       // Maximum 500 B3TR per tonne
            minCarbonAmount: 1e18,           // Minimum 1 tonne to earn rewards
            isActive: true,
            totalRewardsDistributed: 0,
            totalCarbonRewarded: 0
        });
    }

    /**
     * @dev Update reward configuration (only admin)
     * @param baseRewardPerTonne New base reward per tonne
     * @param bonusMultiplier New bonus multiplier (basis points)
     * @param maxRewardPerTonne New maximum reward per tonne
     * @param minCarbonAmount New minimum carbon amount
     * @param isActive Whether rewards are active
     */
    function updateRewardConfig(
        uint256 baseRewardPerTonne,
        uint256 bonusMultiplier,
        uint256 maxRewardPerTonne,
        uint256 minCarbonAmount,
        bool isActive
    ) external onlyRole(REWARD_MANAGER_ROLE) {
        require(baseRewardPerTonne > 0, "VeBetterIntegration: base reward must be positive");
        require(bonusMultiplier >= 10000, "VeBetterIntegration: bonus multiplier must be at least 100%");
        require(maxRewardPerTonne >= baseRewardPerTonne, "VeBetterIntegration: max reward must be >= base reward");
        require(minCarbonAmount > 0, "VeBetterIntegration: min carbon amount must be positive");

        rewardConfig.baseRewardPerTonne = baseRewardPerTonne;
        rewardConfig.bonusMultiplier = bonusMultiplier;
        rewardConfig.maxRewardPerTonne = maxRewardPerTonne;
        rewardConfig.minCarbonAmount = minCarbonAmount;
        rewardConfig.isActive = isActive;

        emit RewardConfigUpdated(baseRewardPerTonne, bonusMultiplier, maxRewardPerTonne, isActive);
    }

    /**
     * @dev Activate/deactivate user for rewards
     * @param user User address
     * @param isActive Whether user is active
     */
    function setUserActive(address user, bool isActive) external onlyRole(REWARD_MANAGER_ROLE) {
        require(user != address(0), "VeBetterIntegration: invalid user address");
        
        bool wasActive = _userRewards[user].isActive;
        _userRewards[user].isActive = isActive;

        if (isActive && !wasActive) {
            _totalUsers++;
            _activeUsers.push(user);
        } else if (!isActive && wasActive) {
            _totalUsers--;
            // Remove from active users array (simplified - in production, use mapping)
        }

        emit UserActivated(user, isActive);
    }

    /**
     * @dev Calculate and record rewards for a carbon credit
     * @param tokenId Carbon credit NFT token ID
     * @param user User who generated the credit
     */
    function calculateReward(uint256 tokenId, address user) 
        external 
        onlyRole(REWARD_MANAGER_ROLE) 
        onlyActiveRewards 
        onlyValidTokenId(tokenId)
        onlyRewardEligible(user)
        nonReentrant 
    {
        require(_creditRewards[tokenId].tokenId == 0, "VeBetterIntegration: reward already calculated");

        // Get carbon credit metadata
        CarbonCreditNFT.CarbonCreditMetadata memory metadata = carbonCreditNFT.getCreditMetadata(tokenId);
        
        require(metadata.carbonAmount >= rewardConfig.minCarbonAmount, "VeBetterIntegration: carbon amount below minimum");
        require(metadata.generatorAddress == user, "VeBetterIntegration: user mismatch");

        // Calculate base reward
        uint256 baseReward = (metadata.carbonAmount * rewardConfig.baseRewardPerTonne) / 1e18;
        
        // Apply bonus for verified credits
        uint256 finalReward = baseReward;
        bool isVerified = metadata.verificationStatus == CarbonCreditNFT.VerificationStatus.Verified;
        
        if (isVerified) {
            finalReward = (baseReward * rewardConfig.bonusMultiplier) / 10000;
        }

        // Apply maximum cap
        if (finalReward > (metadata.carbonAmount * rewardConfig.maxRewardPerTonne) / 1e18) {
            finalReward = (metadata.carbonAmount * rewardConfig.maxRewardPerTonne) / 1e18;
        }

        // Record credit reward info
        _creditRewards[tokenId] = CreditRewardInfo({
            tokenId: tokenId,
            user: user,
            carbonAmount: metadata.carbonAmount,
            b3trReward: finalReward,
            timestamp: block.timestamp,
            isClaimed: false,
            isVerified: isVerified
        });

        // Update user reward info
        UserRewardInfo storage userInfo = _userRewards[user];
        userInfo.totalEarned += finalReward;
        userInfo.pendingRewards += finalReward;
        userInfo.totalCarbonCredits += metadata.carbonAmount;
        userInfo.rewardEligibleCredits += metadata.carbonAmount;

        // Update global stats
        rewardConfig.totalRewardsDistributed += finalReward;
        rewardConfig.totalCarbonRewarded += metadata.carbonAmount;

        // Track user credits
        _userCredits[user].push(tokenId);
        _allRewardedCredits.push(tokenId);

        emit CarbonCreditRewarded(tokenId, user, metadata.carbonAmount, finalReward, isVerified);
    }

    /**
     * @dev Claim pending B3TR rewards
     * @param amount Amount of B3TR to claim (0 = claim all pending)
     */
    function claimRewards(uint256 amount) external onlyRewardEligible(msg.sender) nonReentrant {
        UserRewardInfo storage userInfo = _userRewards[msg.sender];
        
        require(userInfo.pendingRewards > 0, "VeBetterIntegration: no pending rewards");
        
        uint256 claimAmount = amount == 0 ? userInfo.pendingRewards : amount;
        require(claimAmount <= userInfo.pendingRewards, "VeBetterIntegration: insufficient pending rewards");
        require(claimAmount > 0, "VeBetterIntegration: claim amount must be positive");

        // Check B3TR token balance
        IERC20 b3trToken = IERC20(B3TR_TOKEN);
        require(b3trToken.balanceOf(address(this)) >= claimAmount, "VeBetterIntegration: insufficient B3TR balance");

        // Update user info
        userInfo.pendingRewards -= claimAmount;
        userInfo.totalClaimed += claimAmount;
        userInfo.lastClaimTime = block.timestamp;

        // Transfer B3TR tokens
        b3trToken.safeTransfer(msg.sender, claimAmount);

        emit RewardsClaimed(msg.sender, claimAmount, block.timestamp);
    }

    /**
     * @dev Batch claim rewards for multiple users (admin only)
     * @param users Array of user addresses
     * @param amounts Array of amounts to claim for each user
     */
    function batchClaimRewards(address[] calldata users, uint256[] calldata amounts) 
        external 
        onlyRole(CLAIM_MANAGER_ROLE) 
        nonReentrant 
    {
        require(users.length == amounts.length, "VeBetterIntegration: arrays length mismatch");
        require(users.length > 0, "VeBetterIntegration: empty arrays");

        IERC20 b3trToken = IERC20(B3TR_TOKEN);
        uint256 totalClaimAmount = 0;

        // Calculate total claim amount
        for (uint256 i = 0; i < users.length; i++) {
            UserRewardInfo storage userInfo = _userRewards[users[i]];
            uint256 claimAmount = amounts[i] == 0 ? userInfo.pendingRewards : amounts[i];
            totalClaimAmount += claimAmount;
        }

        require(b3trToken.balanceOf(address(this)) >= totalClaimAmount, "VeBetterIntegration: insufficient B3TR balance");

        // Process claims
        for (uint256 i = 0; i < users.length; i++) {
            UserRewardInfo storage userInfo = _userRewards[users[i]];
            uint256 claimAmount = amounts[i] == 0 ? userInfo.pendingRewards : amounts[i];
            
            if (claimAmount > 0 && claimAmount <= userInfo.pendingRewards) {
                userInfo.pendingRewards -= claimAmount;
                userInfo.totalClaimed += claimAmount;
                userInfo.lastClaimTime = block.timestamp;

                b3trToken.safeTransfer(users[i], claimAmount);
                emit RewardsClaimed(users[i], claimAmount, block.timestamp);
            }
        }
    }

    /**
     * @dev Deposit B3TR tokens to the reward pool
     * @param amount Amount of B3TR tokens to deposit
     */
    function depositB3TR(uint256 amount) external nonReentrant {
        require(amount > 0, "VeBetterIntegration: amount must be positive");
        
        IERC20 b3trToken = IERC20(B3TR_TOKEN);
        b3trToken.safeTransferFrom(msg.sender, address(this), amount);
        
        emit B3TRDeposited(msg.sender, amount);
    }

    /**
     * @dev Emergency withdraw B3TR tokens (admin only)
     * @param to Recipient address
     * @param amount Amount to withdraw
     */
    function emergencyWithdraw(address to, uint256 amount) external onlyRole(DEFAULT_ADMIN_ROLE) {
        require(to != address(0), "VeBetterIntegration: invalid recipient address");
        require(amount > 0, "VeBetterIntegration: amount must be positive");
        
        IERC20 b3trToken = IERC20(B3TR_TOKEN);
        require(b3trToken.balanceOf(address(this)) >= amount, "VeBetterIntegration: insufficient balance");
        
        b3trToken.safeTransfer(to, amount);
        emit EmergencyWithdraw(to, amount);
    }

    // View functions
    function getUserRewardInfo(address user) external view returns (UserRewardInfo memory) {
        return _userRewards[user];
    }

    function getCreditRewardInfo(uint256 tokenId) external view returns (CreditRewardInfo memory) {
        require(_creditRewards[tokenId].tokenId != 0, "VeBetterIntegration: no reward info for token");
        return _creditRewards[tokenId];
    }

    function getUserCredits(address user) external view returns (uint256[] memory) {
        return _userCredits[user];
    }

    function getAllRewardedCredits() external view returns (uint256[] memory) {
        return _allRewardedCredits;
    }

    function getActiveUsers() external view returns (address[] memory) {
        return _activeUsers;
    }

    function getTotalUsers() external view returns (uint256) {
        return _totalUsers;
    }

    function getB3TRBalance() external view returns (uint256) {
        IERC20 b3trToken = IERC20(B3TR_TOKEN);
        return b3trToken.balanceOf(address(this));
    }

    function calculatePotentialReward(uint256 carbonAmount, bool isVerified) external view returns (uint256) {
        if (carbonAmount < rewardConfig.minCarbonAmount) {
            return 0;
        }

        uint256 baseReward = (carbonAmount * rewardConfig.baseRewardPerTonne) / 1e18;
        uint256 finalReward = baseReward;
        
        if (isVerified) {
            finalReward = (baseReward * rewardConfig.bonusMultiplier) / 10000;
        }

        uint256 maxReward = (carbonAmount * rewardConfig.maxRewardPerTonne) / 1e18;
        return finalReward > maxReward ? maxReward : finalReward;
    }

    function isUserActive(address user) external view returns (bool) {
        return _userRewards[user].isActive;
    }

    function hasRewardInfo(uint256 tokenId) external view returns (bool) {
        return _creditRewards[tokenId].tokenId != 0;
    }
}
